name: Water Potability MLOps Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 0 * * 0" # Weekly run to check for data drift

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # Install the package in development mode
          pip install -e .

  train-and-evaluate:
    name: Train and Evaluate Model
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    defaults:
      run:
        working-directory: ${{ github.workspace }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Clone DVC cache repo
        run: git clone https://github.com/ty-prct/dvc-cache.git ../dvc-cache
        working-directory: ${{ github.workspace }}

      - name: Configure DVC remote
        working-directory: ${{ github.workspace }}
        run: |
          dvc init
          dvc remote remove cache || true
          dvc remote add -d cache ../dvc-cache/.dvc/cache
          dvc remote modify cache --unset cache.type

          dvc remote list

      - name: Pull data with DVC
        run: |
          # Pull data from the configured remote
          dvc pull --remote cache --verbose --force

      - name: Train model
        run: |
          python src/scripts/train_pipeline.py

      - name: Evaluate model
        run: |
          python src/scripts/evaluate_pipeline.py

      - name: Upload model artifacts
        uses: actions/upload-artifact@v4
        with:
          name: model-artifacts
          path: |
            results/best_model*.pkl
            results/evaluation_results*.json
            results/feature_importance*.csv

      - name: Update DVC tracked files
        run: |
          # Track new model files with DVC
          dvc add models/*.pkl results/best_model*.pkl

          # Push tracked files to the DVC remote
          dvc push -v

          # Configure git for committing changes
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          # Commit and push DVC metadata changes
          git add .
          git commit -m "Update model artifacts [skip ci]" || echo "No changes to commit"
          git push

  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    needs: train-and-evaluate
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4

      - name: Download model artifacts
        uses: actions/download-artifact@v4
        with:
          name: model-artifacts
          path: results/

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/water-potability:latest

      - name: Deploy to production
        run: |
          echo "Deploying to production environment..."
          # Add deployment commands here, e.g., kubectl apply, AWS ECS update, etc.

  model-monitoring:
    name: Model Monitoring
    runs-on: ubuntu-latest
    needs: build-and-deploy
    if: github.event_name == 'schedule'

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run model monitoring
        run: |
          python src/scripts/model_monitoring.py

      - name: Check for drift and trigger retraining if needed
        run: |
          # Logic to check for drift and trigger retraining if detected
          # This would typically analyze the monitoring results and create an issue or trigger workflow
          echo "Checking for model drift..."
