name: Water Potability MLOps Pipeline

permissions:
  contents: write # Grant write access so GH Actions can push commits :contentReference[oaicite:4]{index=4}

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 0 * * 0"

jobs:
  test:
    name: Initialization
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .

  train-and-evaluate:
    name: Train and Evaluate Model
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    defaults:
      run:
        # Ensure DVC commands see .dvc/ in the repo root :contentReference[oaicite:5]{index=5}
        working-directory: ${{ github.workspace }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Configure Git for pushes via PAT
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git remote set-url origin https://x-access-token:${{ secrets.ACTIONS_PAT }}@github.com/${{ github.repository }}.git

      - name: Clone DVC cache repo
        run: git clone https://github.com/yashpotdar-py/dvc-cache ../dvc-cache

      - name: Configure DVC & autostage
        run: |
          # Re-init DVC and enable auto-staging of .dvc metadata :contentReference[oaicite:6]{index=6}
          dvc init --force
          dvc config core.autostage true

          # Set up the cache remote to point at the cloned repo’s blob store
          dvc remote remove cache || true
          dvc remote add -d cache ../dvc-cache/.dvc/cache
          dvc remote modify cache url ../dvc-cache/.dvc/cache
          dvc remote modify cache verify true

          dvc remote list

      - name: Pull data with DVC
        run: dvc pull --remote cache --verbose --force

      - name: Train model
        run: python src/scripts/train_pipeline.py

      - name: Evaluate model
        run: python src/scripts/evaluate_pipeline.py

      - name: Upload model artifacts
        uses: actions/upload-artifact@v4
        with:
          name: model-artifacts
          path: |
            results/best_model*.pkl
            results/evaluation_results*.json
            results/feature_importance*.csv

      - name: Update DVC tracked files & push cache
        run: |
          # Track new model artifacts with DVC
          dvc add models/*.pkl results/best_model*.pkl

          # Push artifacts into the cloned cache :contentReference[oaicite:7]{index=7}
          dvc push -v

          # Commit & push the cache repo so blobs persist :contentReference[oaicite:8]{index=8}
          pushd ../dvc-cache
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git remote set-url origin https://x-access-token:${{ secrets.ACTIONS_PAT }}@github.com/ty-prct/dvc-cache.git
          git add .dvc/cache
          git commit -m "CI: update DVC cache [skip ci]" || echo "No changes"
          git push origin main
          popd

          # Commit the updated DVC metadata in the main repo
          git add .
          git commit -m "CI: update model artifacts [skip ci]" || echo "No changes"
          git push

  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    needs: train-and-evaluate
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4

      - name: Download model artifacts
        uses: actions/download-artifact@v4
        with:
          name: model-artifacts
          path: results/

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/water-potability:latest

      - name: Deploy to production
        run: |
          echo "Deploying to production environment..."

  model-monitoring:
    name: Model Monitoring
    runs-on: ubuntu-latest
    needs: build-and-deploy
    if: github.event_name == 'schedule'

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run model monitoring
        run: python src/scripts/model_monitoring.py

      - name: Check for drift and trigger retraining if needed
        run: echo "Checking for model drift..."
